
package Frontend;

import javax.swing.JOptionPane;

public class FormLogout extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public FormLogout() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelClose = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labMenuDashboard2 = new javax.swing.JLabel();
        labMenuPegawai2 = new javax.swing.JLabel();
        labMenuPenggajian2 = new javax.swing.JLabel();
        labMenuLogout2 = new javax.swing.JLabel();
        iconMenuDashboard2 = new javax.swing.JLabel();
        iconMenuPegawai2 = new javax.swing.JLabel();
        iconMenuPenggajian2 = new javax.swing.JLabel();
        IconMenuLogout2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(225, 225, 225, 150));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel7.setText("Yakin ingin Keluar dari Aplikasi?");

        btnCancelClose.setBackground(new java.awt.Color(117, 255, 52));
        btnCancelClose.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        btnCancelClose.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelClose.setText("Tidak");
        btnCancelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCloseActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 52, 52));
        btnClose.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 0, 0));
        btnClose.setText("Keluar");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/power_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnCancelClose)
                        .addGap(48, 48, 48)
                        .addComponent(btnClose)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelClose)
                    .addComponent(btnClose))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0, 120));
        jPanel6.setPreferredSize(new java.awt.Dimension(280, 492));

        labMenuDashboard2.setBackground(new java.awt.Color(255, 255, 255));
        labMenuDashboard2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuDashboard2.setForeground(new java.awt.Color(225, 225, 225));
        labMenuDashboard2.setText("Dashboard");
        labMenuDashboard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuDashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuDashboard2MouseClicked(evt);
            }
        });

        labMenuPegawai2.setBackground(new java.awt.Color(255, 255, 255));
        labMenuPegawai2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuPegawai2.setForeground(new java.awt.Color(225, 225, 225));
        labMenuPegawai2.setText("Pegawai");
        labMenuPegawai2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuPegawai2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuPegawai2MouseClicked(evt);
            }
        });

        labMenuPenggajian2.setBackground(new java.awt.Color(255, 255, 255));
        labMenuPenggajian2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuPenggajian2.setForeground(new java.awt.Color(225, 225, 225));
        labMenuPenggajian2.setText("Penggajian");
        labMenuPenggajian2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuPenggajian2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuPenggajian2MouseClicked(evt);
            }
        });

        labMenuLogout2.setBackground(new java.awt.Color(255, 255, 255));
        labMenuLogout2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuLogout2.setForeground(new java.awt.Color(225, 225, 225));
        labMenuLogout2.setText("Logout");
        labMenuLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuLogout2MouseClicked(evt);
            }
        });

        iconMenuDashboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard (1).png"))); // NOI18N
        iconMenuDashboard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuDashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuDashboard2MouseClicked(evt);
            }
        });

        iconMenuPegawai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/teamwork (1).png"))); // NOI18N
        iconMenuPegawai2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuPegawai2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuPegawai2MouseClicked(evt);
            }
        });

        iconMenuPenggajian2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/payment (1).png"))); // NOI18N
        iconMenuPenggajian2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuPenggajian2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuPenggajian2MouseClicked(evt);
            }
        });

        IconMenuLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/power (1).png"))); // NOI18N
        IconMenuLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconMenuLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMenuLogout2MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/profile-user (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconMenuDashboard2)
                                    .addComponent(iconMenuPegawai2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labMenuPegawai2)
                                    .addComponent(labMenuDashboard2))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconMenuPenggajian2)
                                    .addComponent(IconMenuLogout2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labMenuLogout2)
                                    .addComponent(labMenuPenggajian2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(70, 70, 70))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuDashboard2)
                    .addComponent(labMenuDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuPegawai2)
                    .addComponent(labMenuPegawai2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuPenggajian2)
                    .addComponent(labMenuPenggajian2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconMenuLogout2)
                    .addComponent(labMenuLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labMenuDashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuDashboard2MouseClicked
        this.setVisible(false);
        new FormDashboard().setVisible(true);
    }//GEN-LAST:event_labMenuDashboard2MouseClicked

    private void labMenuPegawai2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuPegawai2MouseClicked
        this.setVisible(false);
        new FormPegawai().setVisible(true);
    }//GEN-LAST:event_labMenuPegawai2MouseClicked

    private void labMenuPenggajian2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuPenggajian2MouseClicked
        this.setVisible(false);
        new FormPenggajian().setVisible(true);
    }//GEN-LAST:event_labMenuPenggajian2MouseClicked

    private void iconMenuDashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuDashboard2MouseClicked
        this.setVisible(false);
        new FormDashboard().setVisible(true);
    }//GEN-LAST:event_iconMenuDashboard2MouseClicked

    private void iconMenuPegawai2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuPegawai2MouseClicked
        this.setVisible(false);
        new FormPegawai().setVisible(true);
    }//GEN-LAST:event_iconMenuPegawai2MouseClicked

    private void iconMenuPenggajian2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuPenggajian2MouseClicked
        this.setVisible(false);
        new FormPenggajian().setVisible(true);
    }//GEN-LAST:event_iconMenuPenggajian2MouseClicked

    private void btnCancelCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCloseActionPerformed
        this.setVisible(false);
        new FormDashboard().setVisible(true);
    }//GEN-LAST:event_btnCancelCloseActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void IconMenuLogout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuLogout2MouseClicked
        if (evt.getSource() == this) {
            this.setVisible(true);
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_IconMenuLogout2MouseClicked

    private void labMenuLogout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuLogout2MouseClicked
        if (evt.getSource() == this) {
            this.setVisible(true);
        } else {
            this.setVisible(false);
        } 
    }//GEN-LAST:event_labMenuLogout2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconMenuLogout2;
    private javax.swing.JButton btnCancelClose;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel iconMenuDashboard2;
    private javax.swing.JLabel iconMenuPegawai2;
    private javax.swing.JLabel iconMenuPenggajian2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labMenuDashboard2;
    private javax.swing.JLabel labMenuLogout2;
    private javax.swing.JLabel labMenuPegawai2;
    private javax.swing.JLabel labMenuPenggajian2;
    // End of variables declaration//GEN-END:variables
}
