package Frontend;
import Backend.*;
import java.awt.Color;
import java.awt.Image;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javaswingdev.drawer.DrawerItem;
import javax.swing.*;

public class FormDashboard extends javax.swing.JFrame {
    
    private DrawerController drawer;

    public FormDashboard() {
        initComponents();
        showDrawerMenu();
        
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btnMenuDrawer = new javax.swing.JButton();
        dashboardLabel = new javax.swing.JLabel();
        userPicture = new main.ImageAvatar();
        searchField = new javax.swing.JTextField();
        employeePanelCounter = new javax.swing.JPanel();
        employeeId = new javax.swing.JLabel();
        imployeImage = new javax.swing.JLabel();
        employeeCounter = new javax.swing.JLabel();
        salaryPanelCounter = new javax.swing.JPanel();
        salaryId = new javax.swing.JLabel();
        salaryImage = new javax.swing.JLabel();
        salaryCounter = new javax.swing.JLabel();
        tableData = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(650, 500));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(102, 102, 255));
        headerPanel.setForeground(new java.awt.Color(102, 102, 255));

        btnMenuDrawer.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuDrawer.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        btnMenuDrawer.setForeground(new java.awt.Color(102, 102, 255));
        btnMenuDrawer.setText("| | |");
        btnMenuDrawer.setActionCommand("");
        btnMenuDrawer.setIconTextGap(2);
        btnMenuDrawer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDrawerActionPerformed(evt);
            }
        });

        dashboardLabel.setFont(new java.awt.Font("Quicksand", 1, 20)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");

        userPicture.setBorderColor(new java.awt.Color(255, 255, 255));
        userPicture.setBorderSize(2);
        userPicture.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icons/admin.png"))); // NOI18N
        userPicture.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnMenuDrawer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(userPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMenuDrawer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dashboardLabel))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnMenuDrawer.getAccessibleContext().setAccessibleName("");

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Quicksand", 0, 15)); // NOI18N
        searchField.setText("Cari");

        employeePanelCounter.setBackground(new java.awt.Color(255, 102, 102));

        employeeId.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        employeeId.setForeground(new java.awt.Color(255, 255, 255));
        employeeId.setText("Employee");

        imployeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/employee.png"))); // NOI18N

        employeeCounter.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        employeeCounter.setForeground(new java.awt.Color(255, 255, 255));
        employeeCounter.setText("15");

        javax.swing.GroupLayout employeePanelCounterLayout = new javax.swing.GroupLayout(employeePanelCounter);
        employeePanelCounter.setLayout(employeePanelCounterLayout);
        employeePanelCounterLayout.setHorizontalGroup(
            employeePanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeePanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeId)
                    .addGroup(employeePanelCounterLayout.createSequentialGroup()
                        .addComponent(imployeImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeCounter)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        employeePanelCounterLayout.setVerticalGroup(
            employeePanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeePanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imployeImage)
                    .addComponent(employeeCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(employeeId)
                .addContainerGap())
        );

        salaryPanelCounter.setBackground(new java.awt.Color(51, 51, 255));

        salaryId.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        salaryId.setForeground(new java.awt.Color(255, 255, 255));
        salaryId.setText("Salary");

        salaryImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salary.png"))); // NOI18N

        salaryCounter.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        salaryCounter.setForeground(new java.awt.Color(255, 255, 255));
        salaryCounter.setText("15");

        javax.swing.GroupLayout salaryPanelCounterLayout = new javax.swing.GroupLayout(salaryPanelCounter);
        salaryPanelCounter.setLayout(salaryPanelCounterLayout);
        salaryPanelCounterLayout.setHorizontalGroup(
            salaryPanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryPanelCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salaryPanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaryId)
                    .addGroup(salaryPanelCounterLayout.createSequentialGroup()
                        .addComponent(salaryImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryCounter)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        salaryPanelCounterLayout.setVerticalGroup(
            salaryPanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salaryPanelCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salaryPanelCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaryImage)
                    .addComponent(salaryCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(salaryId)
                .addContainerGap())
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Quicksand", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 255));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(true);
        tableData.setViewportView(jTable1);

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(employeePanelCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salaryPanelCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(tableData, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePanelCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryPanelCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tableData, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void showDrawerMenu() {
        ImageIcon dashboardIcon = new ImageIcon(getClass().getResource("/Icons/dashboard.png"));
        ImageIcon employeeIcon = new ImageIcon(getClass().getResource("/Icons/employee.png"));
        ImageIcon salaryIcon = new ImageIcon(getClass().getResource("/Icons/salary.png"));
        ImageIcon logoutIcon = new ImageIcon(getClass().getResource("/Icons/logout.png"));
        
            
        drawer = Drawer.newDrawer(this)
                .header(new HeaderMenu())
                .addChild(new DrawerItem("Dashboard").icon(dashboardIcon).build())
                .addChild(new DrawerItem("Employees").icon(employeeIcon).build())
                .addChild(new DrawerItem("Salary").icon(salaryIcon).build())
                .addFooter(new DrawerItem("Logout").icon(logoutIcon).build())
                .drawerWidth(250)
                .build();
    }
    
    
    
    private void btnMenuDrawerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDrawerActionPerformed
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }//GEN-LAST:event_btnMenuDrawerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnMenuDrawer;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel employeeCounter;
    private javax.swing.JLabel employeeId;
    private javax.swing.JPanel employeePanelCounter;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel imployeImage;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel salaryCounter;
    private javax.swing.JLabel salaryId;
    private javax.swing.JLabel salaryImage;
    private javax.swing.JPanel salaryPanelCounter;
    private javax.swing.JTextField searchField;
    private javax.swing.JScrollPane tableData;
    private main.ImageAvatar userPicture;
    // End of variables declaration//GEN-END:variables
}
