
package Frontend;

import Backend.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class FormPegawai extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public FormPegawai() {
        initComponents();
        
        tampilkanData();
        tampilkanCmbJabatan();
        tampilkanCmbGolongan();
        
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    public void kosongkanForm() {
//        inputNipPegawai.setText("");
//        inputEmailPegawai.setText("");
//        inputNoTelphPegawai.setText("");
//        inputNamaPegawai.setText("");
//        inputAlamatPegawai.setText("");
//
//        dataJabatan.setSelectedIndex(0);
//        dataGolongan.setSelectedIndex(0);
    }
    
    public void tampilkanData() {
        
        String[] kolom = {"ID", "NIP", "Nama", "No. Telp", "Email", "Tanggal Lahir", "Jabatan", "Golongan", "Alamat"};
        ArrayList<Pegawai> listPegawai = new Pegawai().getAll();
        Object[] rowData = new Object[9];

        tblPegawai.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (int i = 0; i < listPegawai.size(); i++) {
            rowData[0] = listPegawai.get(i).getIdPegawai();
            rowData[1] = listPegawai.get(i).getNip();
            rowData[2] = listPegawai.get(i).getNama();
            rowData[3] = listPegawai.get(i).getNoTelp();
            rowData[4] = listPegawai.get(i).getEmail();
            rowData[5] = listPegawai.get(i).getTanggalLahir();
            rowData[6] = listPegawai.get(i).getJabatan().getIdJabatan();
            rowData[7] = listPegawai.get(i).getGolongan().getIdGolongan();
            rowData[8] = listPegawai.get(i).getAlamat();
            
            ((DefaultTableModel) tblPegawai.getModel()).addRow(rowData);
        }
        
    }
    
    public void search(String keyword) {
        
        String[] kolom = {"ID Pegawai", "NIP", "Nama", "No. Telp", "Email", "Tgl. Lahir", "ID Jabatan", "ID Golongan", "Alamat"};
        ArrayList<Pegawai> listPegawai = new Pegawai().search(keyword);
        Object[] rowData = new Object[9];

        tblPegawai.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Pegawai p : listPegawai) {
            rowData[0] = p.getIdPegawai();
            rowData[1] = p.getNip();
            rowData[2] = p.getNama();
            rowData[3] = p.getNoTelp();
            rowData[4] = p.getEmail();
            rowData[5] = p.getTanggalLahir();
            rowData[6] = p.getJabatan().getIdJabatan();
            rowData[7] = p.getGolongan().getIdGolongan();
            rowData[8] = p.getAlamat();
            
            ((DefaultTableModel) tblPegawai.getModel()).addRow(rowData);
        }
        
    }
    
    public void tampilkanCmbJabatan() {
        dataJabatan.setModel(new DefaultComboBoxModel(new Jabatan().getAll().toArray()));
    }
    
    public void tampilkanCmbGolongan() {
        dataGolongan.setModel(new DefaultComboBoxModel(new Golongan().getAll().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        inputNipPegawai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputEmailPegawai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamatPegawai = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnHapusPegawai = new javax.swing.JButton();
        btnTambahBaruPegawai = new javax.swing.JButton();
        btnSimpanPegawai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        inputNoTelphPegawai = new javax.swing.JTextField();
        inputNamaPegawai = new javax.swing.JTextField();
        inputTglLahirPegawai = new javax.swing.JTextField();
        dataJabatan = new javax.swing.JComboBox<>();
        dataGolongan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labMenuDashboard = new javax.swing.JLabel();
        labMenuPegawai = new javax.swing.JLabel();
        labMenuPenggajian = new javax.swing.JLabel();
        labMenuLogout = new javax.swing.JLabel();
        iconMenuDashboard = new javax.swing.JLabel();
        iconMenuPegawai = new javax.swing.JLabel();
        iconMenuPenggajian = new javax.swing.JLabel();
        iconMenuLogout = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PEGAWAI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(225, 225, 225));

        inputNipPegawai.setForeground(new java.awt.Color(0, 0, 0));
        inputNipPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputNipPegawai.setPreferredSize(new java.awt.Dimension(64, 30));
        inputNipPegawai.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel8.setText("NIP");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel9.setText("Nama");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel10.setText("No. Telph");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel11.setText("Email");

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel12.setText("Jabatan");

        inputEmailPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputEmailPegawai.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel13.setText("Golongan");

        inputAlamatPegawai.setColumns(20);
        inputAlamatPegawai.setRows(5);
        inputAlamatPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setViewportView(inputAlamatPegawai);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel14.setText("Alamat");

        btnHapusPegawai.setBackground(new java.awt.Color(255, 87, 87));
        btnHapusPegawai.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        btnHapusPegawai.setForeground(new java.awt.Color(0, 0, 0));
        btnHapusPegawai.setText("Hapus");
        btnHapusPegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHapusPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusPegawai.setFocusable(false);
        btnHapusPegawai.setPreferredSize(new java.awt.Dimension(52, 23));
        btnHapusPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPegawaiActionPerformed(evt);
            }
        });

        btnTambahBaruPegawai.setBackground(new java.awt.Color(252, 255, 87));
        btnTambahBaruPegawai.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        btnTambahBaruPegawai.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahBaruPegawai.setText("Tambah Baru");
        btnTambahBaruPegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTambahBaruPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahBaruPegawai.setFocusable(false);
        btnTambahBaruPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruPegawaiActionPerformed(evt);
            }
        });

        btnSimpanPegawai.setBackground(new java.awt.Color(131, 255, 87));
        btnSimpanPegawai.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        btnSimpanPegawai.setForeground(new java.awt.Color(0, 0, 0));
        btnSimpanPegawai.setText("Simpan");
        btnSimpanPegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpanPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanPegawai.setFocusable(false);
        btnSimpanPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPegawaiActionPerformed(evt);
            }
        });

        tblPegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegawaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPegawai);

        inputNoTelphPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputNoTelphPegawai.setPreferredSize(new java.awt.Dimension(64, 30));

        inputNamaPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputNamaPegawai.setPreferredSize(new java.awt.Dimension(64, 30));

        inputTglLahirPegawai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputTglLahirPegawai.setPreferredSize(new java.awt.Dimension(64, 30));

        dataJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dataJabatan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        dataGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dataGolongan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel1.setText("Tgl. Lahir");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNoTelphPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNipPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(dataJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(dataGolongan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputTglLahirPegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputEmailPegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addComponent(btnSimpanPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambahBaruPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNipPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(dataJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(inputNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpanPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahBaruPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputTglLahirPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHapusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNoTelphPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(inputEmailPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        searchField.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 120));

        labMenuDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labMenuDashboard.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuDashboard.setForeground(new java.awt.Color(225, 225, 225));
        labMenuDashboard.setText("Dashboard");
        labMenuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuDashboardMouseClicked(evt);
            }
        });

        labMenuPegawai.setBackground(new java.awt.Color(255, 255, 255));
        labMenuPegawai.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuPegawai.setForeground(new java.awt.Color(225, 225, 225));
        labMenuPegawai.setText("Pegawai");
        labMenuPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuPegawaiMouseClicked(evt);
            }
        });

        labMenuPenggajian.setBackground(new java.awt.Color(255, 255, 255));
        labMenuPenggajian.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuPenggajian.setForeground(new java.awt.Color(225, 225, 225));
        labMenuPenggajian.setText("Penggajian");
        labMenuPenggajian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuPenggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuPenggajianMouseClicked(evt);
            }
        });

        labMenuLogout.setBackground(new java.awt.Color(255, 255, 255));
        labMenuLogout.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labMenuLogout.setForeground(new java.awt.Color(225, 225, 225));
        labMenuLogout.setText("Logout");
        labMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuLogoutMouseClicked(evt);
            }
        });

        iconMenuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard (1).png"))); // NOI18N
        iconMenuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuDashboardMouseClicked(evt);
            }
        });

        iconMenuPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/teamwork (1).png"))); // NOI18N
        iconMenuPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuPegawaiMouseClicked(evt);
            }
        });

        iconMenuPenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/payment (1).png"))); // NOI18N
        iconMenuPenggajian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuPenggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuPenggajianMouseClicked(evt);
            }
        });

        iconMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/power (1).png"))); // NOI18N
        iconMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuLogoutMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/profile-user (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconMenuDashboard)
                            .addComponent(iconMenuPegawai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labMenuPegawai)
                            .addComponent(labMenuDashboard))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconMenuPenggajian)
                            .addComponent(iconMenuLogout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labMenuLogout)
                            .addComponent(labMenuPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel19)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuDashboard)
                    .addComponent(labMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuPegawai)
                    .addComponent(labMenuPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuPenggajian)
                    .addComponent(labMenuPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMenuLogout)
                    .addComponent(labMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/magnifying-glass (1).png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchField))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        search(searchField.getText());
    }//GEN-LAST:event_btnSearchMouseClicked

    private void iconMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuLogoutMouseClicked
        this.setVisible(false);
        new FormLogout().setVisible(true);
    }//GEN-LAST:event_iconMenuLogoutMouseClicked

    private void iconMenuPenggajianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuPenggajianMouseClicked
        this.setVisible(false);
        new FormPenggajian().setVisible(true);
    }//GEN-LAST:event_iconMenuPenggajianMouseClicked

    private void iconMenuPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuPegawaiMouseClicked
        if (evt.getSource() == this) {
            this.setVisible(true);
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_iconMenuPegawaiMouseClicked

    private void iconMenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuDashboardMouseClicked
        this.setVisible(false);
        new FormDashboard().setVisible(true);
    }//GEN-LAST:event_iconMenuDashboardMouseClicked

    private void labMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuLogoutMouseClicked
        this.setVisible(false);
        new FormLogout().setVisible(true);
    }//GEN-LAST:event_labMenuLogoutMouseClicked

    private void labMenuPenggajianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuPenggajianMouseClicked
        this.setVisible(false);
        new FormPenggajian().setVisible(true);
    }//GEN-LAST:event_labMenuPenggajianMouseClicked

    private void labMenuPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuPegawaiMouseClicked
        if (evt.getSource() == this) {
            this.setVisible(true);
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_labMenuPegawaiMouseClicked

    private void labMenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuDashboardMouseClicked
        this.setVisible(false);
        new FormDashboard().setVisible(true);
    }//GEN-LAST:event_labMenuDashboardMouseClicked

    private void tblPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegawaiMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblPegawai.getModel();
        int row = tblPegawai.getSelectedRow();
        Pegawai pegawai = new Pegawai();

        pegawai = pegawai.getByid(Integer.parseInt(model.getValueAt(row, 0).toString()));
        inputNipPegawai.setText(pegawai.getNip());
        dataJabatan.getModel().setSelectedItem(pegawai.getJabatan().getIdJabatan());
        dataGolongan.getModel().setSelectedItem(pegawai.getGolongan().getIdGolongan());
        inputNamaPegawai.setText(pegawai.getNama());
        inputNoTelphPegawai.setText(pegawai.getNoTelp());
        inputEmailPegawai.setText(pegawai.getEmail());
        inputTglLahirPegawai.setText(pegawai.getTanggalLahir());
        inputAlamatPegawai.setText(pegawai.getAlamat());
    }//GEN-LAST:event_tblPegawaiMouseClicked

    private void btnSimpanPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPegawaiActionPerformed
        Pegawai pegawai = new Pegawai();
        pegawai.setNip(inputNipPegawai.getText());
        pegawai.setNama(inputNamaPegawai.getText());
        pegawai.setTanggalLahir(inputTglLahirPegawai.getText());
        pegawai.setJabatan((Jabatan) dataJabatan.getSelectedItem());
        pegawai.setGolongan((Golongan) dataGolongan.getSelectedItem());
        pegawai.setNoTelp(inputNoTelphPegawai.getText());
        pegawai.setEmail(inputEmailPegawai.getText());
        pegawai.setAlamat(inputAlamatPegawai.getText());

        pegawai.save();
        tampilkanData();
    }//GEN-LAST:event_btnSimpanPegawaiActionPerformed

    private void btnTambahBaruPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruPegawaiActionPerformed
        kosongkanForm();
    }//GEN-LAST:event_btnTambahBaruPegawaiActionPerformed

    private void btnHapusPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPegawaiActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPegawai.getModel();
        int row = tblPegawai.getSelectedRow();

        Pegawai pegawai = new Pegawai().getByid(Integer.parseInt(model.getValueAt(row, 0).toString()));
        pegawai.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusPegawaiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusPegawai;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnSimpanPegawai;
    private javax.swing.JButton btnTambahBaruPegawai;
    private javax.swing.JComboBox<String> dataGolongan;
    private javax.swing.JComboBox<String> dataJabatan;
    private javax.swing.JLabel iconMenuDashboard;
    private javax.swing.JLabel iconMenuLogout;
    private javax.swing.JLabel iconMenuPegawai;
    private javax.swing.JLabel iconMenuPenggajian;
    private javax.swing.JTextArea inputAlamatPegawai;
    private javax.swing.JTextField inputEmailPegawai;
    private javax.swing.JTextField inputNamaPegawai;
    private javax.swing.JTextField inputNipPegawai;
    private javax.swing.JTextField inputNoTelphPegawai;
    private javax.swing.JTextField inputTglLahirPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labMenuDashboard;
    private javax.swing.JLabel labMenuLogout;
    private javax.swing.JLabel labMenuPegawai;
    private javax.swing.JLabel labMenuPenggajian;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tblPegawai;
    // End of variables declaration//GEN-END:variables
}
